-- Adopt pg-persistence's default primary-key names without changing UUID values.
-- PostgreSQL updates existing FK, index and policy dependencies when columns are renamed.
ALTER TABLE public.groups RENAME COLUMN id TO _uuid_id;
ALTER TABLE public.group_members RENAME COLUMN id TO _uuid_id;
CREATE EXTENSION IF NOT EXISTS pg_graphql;

-- Generated by buildViaductEffectiveModel using pg-persistence 0.1.0-pr14.37f74e4-SNAPSHOT.
DO $viaduct_foreign_key$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_constraint constraint_def
      JOIN pg_attribute column_def
        ON column_def.attrelid = constraint_def.conrelid
       AND column_def.attnum = ANY (constraint_def.conkey)
     WHERE constraint_def.contype = 'f'
       AND constraint_def.conrelid =
           'public.group_members'::regclass
       AND column_def.attname = 'group_id'
  ) THEN
    ALTER TABLE "public"."group_members"
      ADD CONSTRAINT "group_members_group_id_fkey"
      FOREIGN KEY ("group_id")
      REFERENCES "public"."groups" ("_uuid_id");
  END IF;
END
$viaduct_foreign_key$;
            DO $viaduct_global_id$
            BEGIN
              IF EXISTS (
                SELECT 1
                  FROM information_schema.columns
                 WHERE table_schema = 'public'
                   AND table_name = 'groups'
                   AND column_name = 'id'
                   AND is_generated = 'NEVER'
              ) THEN
                ALTER TABLE "public"."groups"
                  DROP COLUMN "id";
              END IF;
              IF NOT EXISTS (
                SELECT 1
                  FROM information_schema.columns
                 WHERE table_schema = 'public'
                   AND table_name = 'groups'
                   AND column_name = 'id'
              ) THEN
                ALTER TABLE "public"."groups"
                  ADD COLUMN "id" TEXT GENERATED ALWAYS AS (
                    replace(
                      encode(
                        decode('47726f75703a' || replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(translate(
  "_uuid_id"::text,
  '0123456789abcdef-',
  'GHIJKLMNOPQRSTUVW'
), 'G', '30'), 'H', '31'), 'I', '32'), 'J', '33'), 'K', '34'), 'L', '35'), 'M', '36'), 'N', '37'), 'O', '38'), 'P', '39'), 'Q', '61'), 'R', '62'), 'S', '63'), 'T', '64'), 'U', '65'), 'V', '66'), 'W', '2d'), 'hex'),
                        'base64'
                      ),
                      chr(10),
                      ''
                    )
                  ) STORED NOT NULL;
              END IF;
            END
            $viaduct_global_id$;
            DO $viaduct_global_id$
            BEGIN
              IF EXISTS (
                SELECT 1
                  FROM information_schema.columns
                 WHERE table_schema = 'public'
                   AND table_name = 'group_members'
                   AND column_name = 'id'
                   AND is_generated = 'NEVER'
              ) THEN
                ALTER TABLE "public"."group_members"
                  DROP COLUMN "id";
              END IF;
              IF NOT EXISTS (
                SELECT 1
                  FROM information_schema.columns
                 WHERE table_schema = 'public'
                   AND table_name = 'group_members'
                   AND column_name = 'id'
              ) THEN
                ALTER TABLE "public"."group_members"
                  ADD COLUMN "id" TEXT GENERATED ALWAYS AS (
                    replace(
                      encode(
                        decode('47726f75704d656d6265723a' || replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(translate(
  "_uuid_id"::text,
  '0123456789abcdef-',
  'GHIJKLMNOPQRSTUVW'
), 'G', '30'), 'H', '31'), 'I', '32'), 'J', '33'), 'K', '34'), 'L', '35'), 'M', '36'), 'N', '37'), 'O', '38'), 'P', '39'), 'Q', '61'), 'R', '62'), 'S', '63'), 'T', '64'), 'U', '65'), 'V', '66'), 'W', '2d'), 'hex'),
                        'base64'
                      ),
                      chr(10),
                      ''
                    )
                  ) STORED NOT NULL;
              END IF;
            END
            $viaduct_global_id$;

ALTER TABLE "public"."groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."group_members" ENABLE ROW LEVEL SECURITY;
COMMENT ON SCHEMA "public" IS E'@graphql({"inflect_names": true})';
COMMENT ON TABLE "public"."groups" IS E'@graphql({"name": "Group"})';
COMMENT ON TABLE "public"."group_members" IS E'@graphql({"name": "GroupMember"})';
DO $pg_graphql$
DECLARE
  constraint_name text;
BEGIN
  SELECT constraint_def.conname
    INTO constraint_name
    FROM pg_constraint constraint_def
    JOIN pg_attribute column_def
      ON column_def.attrelid = constraint_def.conrelid
     AND column_def.attnum = ANY (constraint_def.conkey)
   WHERE constraint_def.contype = 'f'
     AND constraint_def.conrelid =
         'public.group_members'::regclass
     AND column_def.attname = 'group_id'
   LIMIT 1;
  IF constraint_name IS NULL THEN
    RAISE EXCEPTION 'No foreign key found for public.group_members.group_id';
  END IF;
  EXECUTE format(
    'COMMENT ON CONSTRAINT %I ON "public"."group_members" IS %L',
    constraint_name,
    '@graphql({"local_name": "members"})'
  );
END
$pg_graphql$;

-- Application-owned defaults and trigger functions are not generated by the library.
ALTER TABLE public.groups ALTER COLUMN owner_id SET DEFAULT auth.uid();
CREATE OR REPLACE FUNCTION public.is_group_owner(group_uuid uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.groups WHERE _uuid_id = group_uuid AND owner_id = auth.uid()
  )
$$;

CREATE OR REPLACE FUNCTION public.add_owner_to_group()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.group_members (group_id, user_id)
  VALUES (NEW._uuid_id, NEW.owner_id)
  ON CONFLICT (group_id, user_id) DO NOTHING;
  RETURN NEW;
END;
$$;
